### PR TITLE
Dev email recovery

### PR DESCRIPTION
**Pull request by HaizeaF**
Email Service for password recovery.
sendEmail: Method that sends an email to the client with the new password.
generateRandomPassword: Method that generates the new password.

### CODE REVIEW

**Comment by STParadox** [comment]
Not ok

**Comment by STParadox** [comment]
good

**Comment by MikelBermejo** [comment]
Ameisin

**Comment by SendoaBadiola** [comment]
Good work🤴🏿👱🏿‍♂️

**Pull request merged**
